#!/bin/sh

url="http://closure-compiler.appspot.com/compile"
dir=`dirname $0`
input="${dir}/workerframe.js"
output="${dir}/workerframe.min.js"

js_code=`cat $input`

curl --silent \
    --data-urlencode "js_code=$js_code" \
    --data-urlencode "output_info=compiled_code" \
    $url > $output
